SignalRClient.xcodeproj/project.pbxproj, SwiftSignalRClient.podspec
Use a lower deployment target in the iOS pod spec to support lower deployment targeted applications.
=> Lower iOS deployment target

.gitignore, Podfile, SwiftSignalRClient.podspec
With the Release of Swift 5, the previous Cocoapod - compiled with 3.3 - is no longer able to be integrated into projects. The minimum supported versions are 4.0, 4.2, and 5.0.
This PR is an addition to the changes I made previously, but would require a new push of the pod to the trunk.
=> Spec bump for swift 4.2 Support

Sources/SignalRClient/JSONHubProtocol.swift
Hi, we need this extension because JSONEncoder and JSONDecoder has different dateDecodingStrategy or dateEncodingStrategy. 
So on custom payload we must support our date format
Another way of solving this issue was subclass JSONHubProtocol, but it little bit complicated because of public class instead of open,  internal PingMessage, custom Logger function and private params.
Or create own HubProtocol implementation with lots of parse logic, that already written in JSONHubProtocol
=> JSONHubProtocol configure with JSONEncoder and JSONDecoder

Sources/SignalRClient/WebSocket.swift
The project will build successfully if built directly, but if you use Swift Package Manager and include SignalR-Client-Swift as a dependency in another project, it will fail with unresolved symbol errors related to zlib. I've attached a simple sample project that proves the issue for easy reference.
[SignalR Test.zip](https://github.com/moozzyk/SignalR-Client-Swift/files/4309259/SignalR.Test.zip)
=> Fix builds using Swift Package Manager

Sources/SignalRClient/WebSocket.swift
This was the only change I needed to make to get this running under watchOS. Given I can test on an iOS device against a self signed cert end point, I have no reason to test the same thing on watchOS, so it's an easy fix for a very large gain. I also played around with #if os(iOS) however this might cut out tvOS, which I have never tried. 
This change is due to the fact that kCFStreamSSLPeerName, kCFStreamSSLValidatesCertificateChain, kCFStreamPropertySSLSettings aren't available on watchOS.
There may be a better way to do what I've done, however in my testing so far its working spot on.
=> Check for watchOS to ignore allowSelfSignedSSL

Sources/SignalRClient/LongPollingTransport.swift
Previously this would give "Fatal error: Double value cannot be converted to Int because the result would be greater than Int.max"
=> Fixed a crash when using long polling on an older device with a 32 bit CPU

Sources/SignalRClient/HubProtocol.swift
Relates to https://github.com/moozzyk/SignalR-Client-Swift/issues/142 .
=> Fix a compiler warning in HubProtocol.swift

Sources/SignalRClient/HttpConnection.swift, Sources/SignalRClient/NegotiationResponse.swift, Tests/SignalRClientTests/HttpConnectionTests.swift, Tests/SignalRClientTests/LongPollingTransportTests.swift, Tests/SignalRClientTests/NegotiationResponseTests.swift
SignalR allows to pass negotiateVersion to opt into new
behaviors/features. With negotiateVersion=1 connectionId is no longer
used to identify the connection. Instead, the client needs to use the
connectionToken it received in the negotiation response as the id
=> Support negotiateVersion

Sources/SignalRClient/HubConnectionBuilder.swift, Tests/SignalRClientTests/HttpConnectionTests.swift, Tests/SignalRClientTests/HubConnectionTests.swift
Fixing tests that failed when running againg Azure SignalR Service due
to races. There were two main issues:
- closing connection from client method handler instead of invocation
completion handler
- closing connection from the server side which can be treated as
graceful closure and hence not a subject to reconnect
=> Fix flaky tests

Sources/SignalRClient/HttpConnectionOptions.swift, Sources/SignalRClient/HubConnectionBuilder.swift
The client was not able to reconnect to Azure SignalR Service if
the service required access token. The problem was that Azure SignalR
Service provides its own token during negotiation and the HttpConnection
overwrote the `accessTokenFactory` provided by the user by an internal
accessTokenFactory that returned the access token returned by Azure
SignalR Service during negotiation. In case of a reconnect the factory
would not be reset and the initial negotiate request would use the
internal access token factory instead of the one provided by the user.
The ultimate issue was that the HttpConnection modified the instance
of HttpConnectionOptions provided by the user. The fix is to create a
shallow copy of HttpConnectionOptions provided by the user when creating
a new instance of …
=> Fix auto reconnect using overriden access token for negotiation

SignalRClient.xcodeproj/project.pbxproj
Relates to https://github.com/moozzyk/SignalR-Client-Swift/issues/142.
Btw, I move the setting from the target and added to the project so all targets share the same thing.
=> Set IPHONEOS_DEPLOYMENT_TARGET to 9.0

.gitignore, README.md, Sources/SignalRClient/DefaultTransportFactory.swift, Sources/SignalRClient/HttpConnection.swift, Sources/SignalRClient/HttpConnectionOptions.swift, Sources/SignalRClient/HubConnection.swift, Sources/SignalRClient/HubConnectionBuilder.swift, Sources/SignalRClient/HubConnectionDelegate.swift, Sources/SignalRClient/HubConnectionExtensions.swift, Sources/SignalRClient/JSONHubProtocol.swift, Sources/SignalRClient/ReconnectPolicy.swift, Sources/SignalRClient/ReconnectableConnection.swift, Sources/SignalRClient/StreamHandle.swift, Sources/SignalRClient/WebsocketsTransport.swift, Tests/SignalRClientTests/HandshakeProtocolTests.swift, Tests/SignalRClientTests/HttpConnectionTests.swift, Tests/SignalRClientTests/HubConnectionTests.swift
A few things here:
* macOS documentation: macOS Monterey has an 'AirPlay Receiver' bound to port 5000 by default. Added instructions on disabling the receiver so the test server can start correctly.
* Comment wrapping: wrapped especially long comment lines to make it easier to read documentation in-line.
* Spelling corrections
=> macOS Monterey Documentation

Sources/SignalRClient/HttpConnection.swift
The `sendKeepAlivePing` function is called on the `hubConnectionQueue`, and the `resetKeepAlive` function needs to acquire this queue to do its work.
If `HttpConnection` calls its `sendDidComplete` function synchronously, this results in a deadlock since `resetKeepAlive` is called inside the `hubConnectionQueue`. This PR ensures that the disconnected state sends completion asynchronously.
Obviously, there are other ways to do this – I'm happy for you to change the queue or avoid the deadlock another way. This PR is as much an FYI as a solution.
=> Avoid a synchronous callback which can deadlock the keep alive ping.

Sources/SignalRClient/HubConnection.swift
Hi Pawel,
As I mentioned in my other PR, I'm investigating why our server is choosing to close socket connections periodically.
I'm trying an experiment where I've removed the call to `resetKeepAlive` in `connectionDidReceiveData`. At the moment, it appears that this change avoids the problem I was having.
I don't know if this is correct. I don't really know what communication the SignalR server is supposed to use to keep the connection alive. I'm not even totally sure how our server is configured (it's out of my control). But I wanted to let you know the result of my experiment.
Cheers,
Matt.
=> Don't call `resetKeepAlive` in `connectionDidReceiveData`.

Sources/SignalRClient/ReconnectableConnection.swift
This PR is a follow up to https://github.com/moozzyk/SignalR-Client-Swift/pull/238
After fixing that bug, we're now seeing a deadlock in our analytics in `ReconnectableConnection`. For exactly the same reasons as `HttpConnection`, an asynchronous callback from `ReconnectableConnection` can cause a deadlock with the `keepAlivePing` so the `sendDidComplete` should always be sent asynchronously.
=> Avoid asynchronous callback on ReconnectableConnection, too.

Sources/SignalRClient/HttpConnectionOptions.swift, Sources/SignalRClient/HubConnectionBuilder.swift
Websocket task is not supported on some older OSX, iOS, watchOS and tvOS versions and the client will fallback to longPolling. However it was still possible to set the `skipNegotiation` to `true` which forced creating a webSocket transport which failed because the webSocket transport was not supported. This change blocks the ability to set `skipNegotiation` if the webSocket transport is not supported.
Fixes: #252
=> Block setting skipNegotiation if webSocket transport is not available

Sources/SignalRClient/HubConnectionBuilder.swift
Add authenticationChallengeHandler to httpConnectionOptionsCopy, otherwise completion handler is not called when used from client
=> Fix incomplete delegate HubConnectionBuilder allocation

Sources/SignalRClient/ReconnectableConnection.swift, Tests/SignalRClientTests/ReconnectableConnectionTests.swift
I faced an issue when the connection gets a stop request when it is in the `disconnected` state. 
This could happen when switching the tab very quickly or getting the app in background and opening it quickly. 
The connection will then not be able to restart.
1. Start a connection
1. Stop the connection
1. Then call `stop()` again
1. Try to start the connection again : the connection could not be started, we get :
> Reconnectable connection not in the disconnected state. Ignoring start request
The connection should be able to start again
When calling `stop()` (`ReconnectableConnection` class) for the second time, it will change the state directly to `stopping` (without checking the current state). 
Then it will call `underlyingConnection.stop(stopError: stopError)` 
In the stop function …
=> Fixing a bug when stopping a disconnected connection

Sources/SignalRClient/HttpConnectionOptions.swift, Sources/SignalRClient/HubConnectionBuilder.swift, Sources/SignalRClient/WebsocketsTransport.swift
- exposes `maximumWebsocketMessageSize` via `HttpConnectionOptions` so that `maximumMessageSize` can be set on `URLSessionWebSocketTask`
- this is needed to be able to set larger buffer sizes than Apple's default
=> add ability to specify the URLSessionWebSocketTask maximumMessageSize

Sources/SignalRClient/ReconnectPolicy.swift
Added `InfiniteReconnectPolicy` for systems that require reconnection whenever is possible. The `InfiniteReconnectPolicy` takes last `retryInterval` and repeats it infinitely, when last `retryInterval` was reached.
My team is using .NET with SignalR in the backend, and this ReconnectPolicy is crucial for our iOS app to work seamlessly. Therefore I'd appreciate this change being part of the original repository :)
=> Added an InfiniteReconnectPolicy.
